<?php

namespace App\JsonApi\V1\SalesManagement\Invoices;

use Illuminate\Http\Request;
use LaravelJsonApi\Core\Auth\Authorizer as JsonApiAuthorizer;

class Authorizer extends JsonApiAuthorizer {

    public function index(Request $request, string $modelClass): bool
    {
        return true;
        //return parent::index($request, $modelClass); // TODO: Change the autogenerated stub
    }


    public function show(Request $request, $model): bool
    {
        return true;
        //return parent::index($request, $modelClass); // TODO: Change the autogenerated stub
    }

    public function destroy(Request $request, $model): bool
    {
        return true;
        //return parent::index($request, $modelClass); // TODO: Change the autogenerated stub
    }


    public function update(Request $request, $model): bool
    {
        return true;
        //return parent::index($request, $modelClass); // TODO: Change the autogenerated stub
    }



}
